default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  port: <%= ENV["DATABASE_PORT"].present? ? ENV["DATABASE_PORT"].to_i : 5432 %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: 5

test:
  <<: *default
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: 5

production:
  <<: *default
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  port: <%= ENV["DATABASE_PORT"].present? ? ENV["DATABASE_PORT"].to_i : 5432 %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: <%= ENV["DATABASE_POOL"].present? ? ENV["DATABASE_POOL"].to_i : 5 %>

