default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  hostname: 127.0.0.1

development:
  <<: *default
  database: flashcards_development

test:
  <<: *default
  database: flashcards_test